### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by Ayowel** [Ayowel/renpy-setup-action#12]
* [ ] Ensure coverage is sufficient
* On `develop`:
  * [ ] Pull upstream changes
  * [ ] Create new branch `releases/vX.X.X`
  * [ ] Update README versions
  * [ ] Update package.json versions
  * [ ] Build `dist` file (`npm run-script build`)
  * [ ] Commit changes with `Prepare release vX.X.X`
* [ ] Run manual integration tests
* [ ] Prepare [changelog](https://github.com/Ayowel/renpy-setup-action/wiki/Changelog)
* [ ] Tag commit
* [ ] Create release with changelog info
* [ ] Verify release workflow ends without errors
* [ ] Fast-forward master (`git push origin releases/vX.X.X:master`)
